trigger:
  branches:
    include:
      - main  

variables:
  - group: AzureSecrets  # Reference the Azure variable group
  - name: imageName
    value: 'flask-microservice'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Code'

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'flask-docker-connection'  # Azure service connection for ACR
    repository: 'flaskappcontainerregistry.azurecr.io/flask-microservice'  
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: latest
