trigger:
  branches:
    include:
      - main

variables:
  - name: imageName
    value: 'flask-microservice'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    steps:
    - checkout: self
      displayName: 'Checkout Code'
    
    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'flask-docker-connection'
        repository: 'flaskappcontainerregistry.azurecr.io/flask-microservice'  
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: latest

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      displayName: 'Azure Container Registry Login'
      inputs:
        azureSubscription: 'flask-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal \
            -u $(servicePrincipalId) \
            -p $(servicePrincipalKey) \
            --tenant $(tenantId)
          
          az acr login -n flaskappcontainerregistry

    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Apps'
      inputs:
        azureSubscription: 'jashan-sp-azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp create \
            --name flask-app \
            --resource-group flask-microservice-rg \
            --image flaskappcontainerregistry.azurecr.io/flask-microservice:latest \
            --environment flask-container-environment \
            --cpu 0.5 --memory 1Gi \
            --min-replicas 2 --max-replicas 3 \
            --ingress 'external' \
            --target-port 8080
