trigger:
  branches:
    include:
      - main
  
variables: 
  - group: flask-microservice-vars  # Recommended: Use variable groups for sensitive info
  - name: imageName
    value: 'flask-microservice'
  - name: imageTag
    value: '$(Build.BuildId)'
  - name: containerRegistry
    value: 'flaskappcontainerregistry.azurecr.io'
  - name: registryName
    value: 'flaskappcontainerregistry'
  - name: resourceGroup
    value: 'flask-microservice-rg'
  - name: containerAppName
    value: 'flask-app'
  - name: containerEnvironment
    value: 'flask-container-environment'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build and Push Stage'
    jobs:
      - job: Build
        displayName: 'Docker Build and Push'
        steps:
          - checkout: self
            displayName: 'Checkout Repository'
            fetchDepth: 1
          
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'jk-docker-connection'
              repository: '$(imageName)'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(imageTag)
                latest
            
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Deployment Artifacts'
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'flask-microservice-artifacts'
    
  - stage: Deploy
    displayName: 'Deploy to Azure Container Apps'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Container App Deployment'
        steps:
          - task: AzureCLI@2
            displayName: 'Azure Container Registry Login'
            inputs:
              azureSubscription: 'jk-sp-azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Login to Azure Container Registry
                az acr login --name $(registryName)
                
                # Verify image exists
                IMAGE_EXISTS=$(az acr repository show-tags \
                  --name $(registryName) \
                  --repository $(imageName) \
                  --query "contains(@, '$(imageTag)')" \
                  --output tsv)
                
                if [ "$IMAGE_EXISTS" != "true" ]; then
                  echo "Error: Image not found in registry"
                  exit 1
                fi
          
          - task: AzureCLI@2
            displayName: 'Deploy to Azure Container Apps'
            inputs:
              azureSubscription: 'jk-sp-azure'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Ensure container environment exists
                az containerapp env show \
                  --name $(containerEnvironment) \
                  --resource-group $(resourceGroup) \
                  || az containerapp env create \
                  --name $(containerEnvironment) \
                  --resource-group $(resourceGroup)
                
                # Check if container app exists, update or create accordingly
                if az containerapp show --name $(containerAppName) --resource-group $(resourceGroup) &>/dev/null; then
                  echo "Updating existing container app..."
                  az containerapp update \
                    --name $(containerAppName) \
                    --resource-group $(resourceGroup) \
                    --image $(containerRegistry)/$(imageName):$(imageTag)
                else
                  echo "Creating new container app..."
                  az containerapp create \
                    --name $(containerAppName) \
                    --resource-group $(resourceGroup) \
                    --image $(containerRegistry)/$(imageName):$(imageTag) \
                    --environment $(containerEnvironment) \
                    --cpu 0.5 \
                    --memory 1Gi \
                    --min-replicas 1 \
                    --max-replicas 3 \
                    --ingress 'external' \
                    --target-port 5000
                fi
                
                # Verify and output deployment details
                az containerapp show \
                  --name $(containerAppName) \
                  --resource-group $(resourceGroup) \
                  --query "{name:name, status:properties.provisioningState, url:properties.configuration.ingress.fqdn}" \
                  --output jsonc
