trigger:
  branches:
    include:
      - main

variables:
  - group: AzureSecrets  # Reference the Azure variable 
  - name: imageName
    value: 'flask-microservice'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    steps:
    - checkout: self
      displayName: 'Checkout Code'

    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'flask-docker-connection'  # Azure service connection for ACR
        repository: 'flaskappcontainerregistry.azurecr.io/flask-microservice'  
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: latest

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Apps'
      inputs:
        azureSubscription: 'flask-connection'  # Update with your Azure service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp create \
            --name flask-app \
            --resource-group flask-microservice-rg  # Update with your resource group
            --image flaskappcontainerregistry.azurecr.io/flask-microservice:latest \
            --environment flask-container-environment  # Update with your Azure Container App environment
            --cpu 0.5 --memory 1Gi \
            --min-replicas 2 --max-replicas 3 \
            --ingress 'external' \
            --target-port 8080
