trigger:
  branches:
    include:
      - main
  
variables: 
  - name: imageName
    value: 'flask-microservice'
  - name: imageTag
    value: '$(Build.BuildId)'
  - name: containerRegistry
    value: 'flaskappcontainerregistry.azurecr.io'
  - name: registryName
    value: 'flaskappcontainerregistry'
  - name: resourceGroup
    value: 'jashan-flask-rg'
  - name: sp_app_id
    value: '$(sp_app_id)'
  - name: sp_password
    value: '$(sp_password)'
  - name: sp_tenant
    value: '$(sp_tenant)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build and Push Stage'
    jobs:
      - job: Build
        displayName: 'Docker Build and Push'
        steps:
          - checkout: self
            displayName: 'Checkout Repository'
            fetchDepth: 1

          # Step to login to Azure using Service Principal
          - task: AzureCLI@2
            displayName: 'Azure CLI Login'
            inputs:
              azureSubscription: '945fce6d-95d4-4e5e-9105-7180e12eb891'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging in to Azure..."
                az login --service-principal -u $(sp_app_id) -p $(sp_password) --tenant $(sp_tenant)
                echo "Logging in to ACR..."
                az acr login --name $(registryName)

          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'jk-docker-connection' # Ensure this service connection is configured correctly
              repository: '$(imageName)'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(imageTag)
                latest