trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'flask-microservice'
  - group: AzureSecrets  # Reference the Azure variable group

steps:
- task: Checkout@1
  displayName: 'Checkout Code'

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'flask-docker-connection'  # Azure service connection for ACR
    repository: 'flaskappcontainerregistry.azurecr.io/flask-microservice'  
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      latest
